name: 'nyc_project'
version: '1.0'
profile: 'nyc_project'
require-dbt-version: [">=1.3.0", "<2.0.0"]
config-version: 2

target-path: /tmp/target
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: /tmp/dbt_logs
packages-install-path: /tmp/dbt_packages

models:
  nyc_project:
      # Applies to all files under models/.../
      staging:
          +schema: staging
          +materialized: view
      marts: 
        warehouse: 
          +schema: staging
        reporting: 
          +materialized: table

vars:
  green_warn_rules:
    - name: pickup_datetime_future
      condition: "pickup_datetime <= current_timestamp()"
      description: "Pickup datetime should not be in the future"
    - name: invalid_fare_amount
      condition: "fare_amount >= 0"
      description: "Fare amount should be non-negative"
    - name: missing_passenger_count
      condition: "passenger_count IS NOT NULL"
      description: "Passenger count should not be null"
    - name: unusual_trip_distance
      condition: "trip_distance BETWEEN 0 AND 100"
      description: "Trip distance should be within 0-100 miles"

  green_drop_rules:
    - name: null_pickup_datetime
      condition: "pickup_datetime IS NOT NULL"
      description: "Pickup datetime must not be null"
    - name: null_dropoff_datetime
      condition: "dropoff_datetime IS NOT NULL"
      description: "Dropoff datetime must not be null"
    - name: negative_total_amount
      condition: "total_amount > 0"
      description: "Total amount must be positive"