name: 'retail'
version: '1.0'
profile: 'retail'
require-dbt-version: [">=1.3.0", "<2.0.0"]
config-version: 2

target-path: /tmp/target
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: /tmp/dbt_logs
packages-install-path: /tmp/dbt_packages

models:
  retail:
    materialized: table