version: 2 

sources: 
  - name: base 
    database: sigma-heuristic-457716-n7

    tables: 
      - name: raw_green_trips 
        description: Source table for green taxi trips 
      
      - name: raw_yellow_trips 
        description: Source table for yellow taxi trips

      - name: raw_fhv_trips 
        description: Source table for yellow taxi trips

      - name: raw_fhvhv_trips 
        description: Source table for yellow taxi trips

